name: Publish ZIP

on:
  push:
    branches: [main, v2]

# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
concurrency:
  group: "pages"

# Grant GITHUB_TOKEN the permissions required to make a Pages deployment
permissions:
  pages: write # to deploy to Pages
  id-token: write # to verify the deployment originates from an appropriate source

jobs:
  # Build job
  zip:
    name: Create Bloodpoint-Farming-Macros.zip
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Create ZIP
        run: |
          mkdir output
          zip -r output/Bloodpoint-Farming-Macros.zip *.ahk Lib icons/*.ico

      - name: Upload static files as artifact
        id: deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: output/

  # Deployment job
  deploy:
    name: Publish Bloodpoint-Farming-Macros.zip
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: zip
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
